app/mod_main/models.py
"""Defines database models."""

from app import db


class Base(db.Model):
    """Defines base parent model to inherit to other classes."""

    __abstract__ = True

    id = db.Column(db.Integer, primary_key=True)
    date_created = db.Column(db.DateTime, default=db.func.current_timestamp())
    date_modified = db.Column(db.DateTime, default=db.func.current_timestamp(),
                              onupdate=db.func.current_timestamp())


class Project(Base):
    """Extend Base to include project attributes."""

    __tablename__ = 'project'

    # Project Name
    name = db.Column(db.String(70), nullable=False, unique=True)
    # Link to project
    link = db.Column(db.String(512), nullable=False, unique=True)
    # Link to source code
    src = db.Column(db.String(512), nullable=True, unique=True)
    # Description
    desc = db.Column(db.String(2000), nullable=True, unique=True)

    def __repr__(self):
        """Evaluate new instance (success/fail)."""
        return '<Project %r>' % self.name

def __init__(self, name, link, src, desc):
    """Instantiate new instance."""
    self.name = name
    self.link = link
    self.src = src
    self.desc = desc

app/__init__.py
"""Create Flask object application."""

from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

# Configurations
app.config.from_object('config')
db = SQLAlchemy(app)

# Error Handling
@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404

from app.mod_main.controllers import MOD_MAIN as main_module
from app.mod_auth.controllers import MOD_AUTH as auth_module

app.register_blueprint(main_module)
app.register_blueprint(auth_module)
db.create_all()

app/mod_auth/controllers.py
"""Render MOD_AUTH templates."""

from flask import Blueprint, request, render_template, redirect, url_for
from app import db
from app.mod_main.models import Project


MOD_AUTH = Blueprint('auth', __name__, url_prefix='/')


@MOD_AUTH.route('/admin', methods=['GET', 'POST'])
def admin():
    """Render admin."""
    title = "Admin Login | James He"
    return render_template("auth/admin.html", title=title)

@MOD_AUTH.route('/admin/CRUD', methods=['GET', 'POST'])
def crud():
    """Renders projects."""
    title = "Admin Dashboard | James He"
    return render_template("auth/crud.html", title=title)

app/mod_main/controllers.py
"""Render MOD_MAIN templates."""

from flask import Blueprint, request, render_template, redirect, url_for
from app import db
from app.mod_main.models import Project 


MOD_MAIN = Blueprint('main', __name__, url_prefix='/')


@MOD_MAIN.route('/', methods=['GET', 'POST'])
def home():
    """Render home page."""
    title = "Home | James He"
    return render_template("main/home.html", title=title)

@MOD_MAIN.route('/projects', methods=['GET', 'POST'])
def projects():
    """Renders projects."""
    title = "Projects | James He"
    return render_template("main/projects.html", title=title)

@MOD_MAIN.route('/blog', methods=['GET', 'POST'])
def blog():
    """Renders blog directory"""
    title = "Blog | James He"
    return render_template("main/blog.html", title=title)

app/templates/main/blog.html
{% extends "main/layout.html" %}

{% block content %}
<section class="hero">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                Blog Posts
            </h1>
            <h2 class="subtitle">
                Things I've written, sorted by most recent.
            </h2>
        </div>
    </div>
</section>

{% endblock content %}

app/templates/main/home.html
{% extends "main/layout.html" %}

{% block content %}
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Hi, I'm James. Welcome to my website.
      </h1>
      <h2 class="subtitle">
        I'm a developer, business student, and writer with many other hobbies.
      </h2>
      <div class="content">
        <p class="is-large">
          I'm located in Bloomington, IN, attending Indiana University
          double majoring in Finance & Information Systems. Currently,
          I serve as the project lead developer for Doriot, Inc., working on the
          first iteration of the
          <a href="https://www.doriot.com/?mwr=jamesfce1">
          Fantasy Startup app</a>. For fun, I produce and host my podcast,
          <a href="">No Coast Oriental</a>. I also write about whatever I
          choose to write about.
        </p>
        <p class="is-large">
          This site serves as my portfolio, blog, and hub for certain personal
          projects.
        </p>
        <p class="is-large">Feel free to take a look around!</p>
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/main/layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <!-- links bulma stylesheet -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="../../static/css/bulma.css">
    <link rel="stylesheet" type="text/css" href="../../static/css/main.css">

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>James He</title
    {% endif %}
  </head>

  <body>
    <!-- navbar -->
    <nav class="navbar is-transparent has-shadow is-spaced" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item"><strong>James He</strong></a>
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div id="mainNavbarMenu" class="navbar-menu">
        <div class="navbar-start">
          <!--navbar items still need LINKS!!!-->
	        <a href={{ url_for('main.home') }} class="navbar-item">Home</a>
	        <a href={{ url_for('main.projects') }} class="navbar-item">Projects</a>
          <a href={{ url_for('main.blog') }} class="navbar-item">Blog</a>
          <a class="navbar-item">About</a>
        </div>
        <div class="navbar-end">
          <a class="navbar-item">Github</a>
        </div>
      </div>
    </nav>

    <main role="main" class="container">
      {% block content %}{% endblock %}
    </main>
  </body>

  <footer class='footer'>
    <div class="content has-text-centered">
      <p>
        <strong>jameshe.me</strong> is developed by me, <a href="http://www.jameshe.me">James He</a>
        <br>
        View this website on <strong><a href="https://www.github.com/he-james">Github</a></strong>
      </p>
		
  	  <a href={{ url_for('auth.admin') }}>Admin</a>

    </div>
  </footer>
</html>

app/templates/main/projects.html
{% extends "main/layout.html" %}

{% block content %}
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        My Projects 
      </h1>
			<div class="column is-mobile">
				<div class="column">
				  <div class="box">
						<div class="content">
						  First Item
						</div>
					</div>
				</div>
			</div>
    </div>
  </div>
</section>
{% endblock %}